version: '2.4'

volumes:
  postgres_data:

services:


  db:
    image: kartoza/postgis:11.5-2.8
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../webhost/.env.dev.db
    ports:
      - "5433:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    restart: always
    image: discord_bot/web
    build:
      context: ../webhost
      dockerfile: ./Docker/Dockerfile.local
    ports:
      - "127.0.0.1:8000:8000"
      - "80:80"
    depends_on:
      - redis
      - db
    volumes:
      - ../webhost:/code
    env_file:
      - ../webhost/.env.dev

  celery:
    restart: always
    image: discord_bot/celery
    build:
      context: ../webhost
      dockerfile: ./Docker/Dockerfile.celery
    depends_on:
      - redis
    env_file:
      - ../webhost/.env.dev

  flower:  
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:  
      - "8888:8888"
