version: '2.4'

volumes:
  postgres_data:
  static_volume:

services:

  nginx:
    image: discord_bot/nginx_prod
    build: ../webhost/nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
      - flower

  db:
    image: kartoza/postgis:11.5-2.8
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../webhost/.env.prod.db

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    restart: always
    image: discord_bot/web_prod
    build:
      context: ../webhost
      dockerfile: ./Docker/Dockerfile.prod
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    depends_on:
      - redis
      - db
    env_file:
      - ../webhost/.env.prod

  celery:
    restart: always
    image: discord_bot/celery_prod
    build:
      context: ../webhost
      dockerfile: ./Docker/Dockerfile.celery
    depends_on:
      - redis
    env_file:
      - ../webhost/.env.prod

  flower:  
    image: mher/flower
    command: ['flower', '--broker=redis://redis:6379', '--port=8888', '--url_prefix=flower']
    ports:  
      - "8888:8888"
    depends_on:
      - redis
      - celery
