# Generated by Django 4.0.4 on 2022-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_moneylog_bot_balance_bot_total_earned_delete_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('collecter', 'Collecter'), ('bumper', 'Bumper')], default='disabled', max_length=100),
        ),
    ]
