# Generated by Django 4.0.4 on 2022-05-16 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.money', verbose_name='bot'),
        ),
    ]
