# Generated by Django 4.0.4 on 2022-05-16 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_bot_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='money',
        ),
        migrations.AddField(
            model_name='money',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.bot', verbose_name='bot'),
            preserve_default=False,
        ),
    ]
