# Generated by Django 4.0.4 on 2022-05-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_bot_money_money_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bot', verbose_name='money'),
        ),
    ]
