version: '2.4'

volumes:
  postgres_data:
  static_volume:

services:

  nginx:
    image: discord_bot/nginx
    build: ../webhost/nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
      - flower

  db:
    image: kartoza/postgis:11.5-2.8
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../webhost/.env.dev.db
    ports:
      - "5433:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    restart: always
    image: discord_bot/web
    build:
      context: ../webhost
      dockerfile: ./Docker/Dockerfile.local
    expose:
      - 8000
    depends_on:
      - redis
      - db
    volumes:
      - ../webhost:/code
      - static_volume:/code/staticfiles
    env_file:
      - ../webhost/.env.dev

  celery:
    restart: always
    image: discord_bot/celery
    build:
      context: ../webhost
      dockerfile: ./Docker/Dockerfile.celery
    depends_on:
      - redis
    env_file:
      - ../webhost/.env.dev

  flower:
    image: mher/flower
    env_file:
      - ../webhost/.env.dev.flower
    ports:
      - "8888:8888"
    depends_on:
      - redis
      - celery
