# Generated by Django 4.0.4 on 2022-05-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='pocket_balance',
            new_name='cash_balance',
        ),
        migrations.RenameField(
            model_name='moneylog',
            old_name='earned',
            new_name='value',
        ),
        migrations.AddField(
            model_name='balance',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balance',
            name='text_earned',
            field=models.IntegerField(default=0),
        ),
    ]
