# Generated by Django 4.0.4 on 2022-05-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='total_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Money',
        ),
        migrations.AddField(
            model_name='moneylog',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='money', to='backend.bot'),
        ),
    ]
