# Generated by Django 4.0.4 on 2022-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bot_bot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='bot_type',
        ),
        migrations.AddField(
            model_name='bot',
            name='role',
            field=models.CharField(choices=[('disabled', 'disabled'), ('collecter', 'collecter'), ('bumper', 'bumper'), ('collecter_and_bumper', 'collecter_and_bumper')], default='disabled', max_length=100),
        ),
    ]
