# Generated by Django 4.0.4 on 2022-05-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_bot_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_work_task', models.DateTimeField(auto_now_add=True)),
                ('next_crime_task', models.DateTimeField(auto_now_add=True)),
                ('next_collect_task', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='backend.taskschedule'),
        ),
    ]
