# Generated by Django 4.0.4 on 2022-05-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_moneylog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
