# Generated by Django 4.0.4 on 2022-05-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_errorlog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylog',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
