# Generated by Django 4.0.4 on 2022-05-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_moneylog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='total_earned',
        ),
        migrations.AlterField(
            model_name='moneylog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_log', to='backend.bot'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_balance', models.IntegerField(default=0)),
                ('bank_balance', models.IntegerField(default=0)),
                ('work_earned', models.IntegerField(default=0)),
                ('collect_earned', models.IntegerField(default=0)),
                ('crime_earned', models.IntegerField(default=0)),
                ('crime_loss', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='backend.bot')),
            ],
        ),
    ]
